### ISSUE TITLE
questions about rah_memcached

### ISSUE THREAD

**Issue by maniqui** [gocom/rah_memcached#1]
(Yeah, I know, the subject for this issue sucks!)

Hi, gocom. 
I've just found this new rah thing. Looks nice!
I've yet to install it and give it a try. In the meanwhile, I've a few questions:

1) Does this plugin provide a similar functionality to [aks_cache](http://textpattern.org.ua/plugins/aks_cache)? It seems so, but I've to ask. 

2) I see the plugin provides some cache flushing mechanism on content updates. Does it also provide any mechanism (a GUI?) to flush the cache "manually"?

3) Tangentially related: what about rah_cache? Is it still under ongoing development (seems not) or should I forget about it? (I've installed it on a project but never found the time to configure and test it properly).

Thank you.

**Comment by gocom** [comment]
> 1) Does this plugin provide a similar functionality to aks_cache?

Yes, kind of. Main differences are that rah_memcached uses Memcached, dedicated in-memory key-value caching server, has bytecode caching features (is able to store variables in memory) and is technically able to use server arrays, rather than being centralized.

> Does it also provide any mechanism (a GUI?) to flush the cache "manually"?

No, there is no need to. The cache is by default flushed on content updates (as long as `lastmod` is the default `1` on the block). Any GUI would just be extra bloat.

For static template sections that don't need flushing, the `lastmod` can be disabled, and cache can be invalidated manually (through memcached). Any cached block that doesn't have name uses MD5 checksum of the content, so it would invalidate automatically if the wrapped markup changes. Or the name can be set to contain something that changes over time.

If you want to manage and inspect the cache, you can use any Memcached management utility (or just straight CLI) if you so wish to; the PHP extensions comes with statistics printing method too.

> Tangentially related: what about rah_cache? Is it still under ongoing development (seems not) or should I forget about it? (I've installed it on a project but never found the time to configure and test it properly).

Different things for different things. Rah_cache is a full-page cache (making it not so useful for sites containing dynamic, user-private content), rah_memcached is a key-value storage. Sure, I haven't touched rah_cache in 2 years, but it works.
